"""initial migration

Revision ID: 58a6d0554597
Revises: 
Create Date: 2025-11-15 19:49:53.311100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a6d0554597'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email_verification_code', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%'", name='check_email_format'),
    sa.CheckConstraint("role IN ('user', 'premium', 'admin')", name='check_user_role'),
    sa.CheckConstraint("status IN ('pending', 'active', 'suspended', 'deactivated')", name='check_user_status'),
    sa.CheckConstraint('length(first_name) >= 1 AND length(last_name) >= 1', name='check_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_verification_code'),
    sa.UniqueConstraint('password_reset_token')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'INVESTMENT', 'CREDIT', 'BUSINESS', name='accounttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', 'PENDING', name='accountstatusenum'), nullable=True),
    sa.Column('current_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('pending_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('reserved_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('overdraft_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_overdraft_enabled', sa.Boolean(), nullable=True),
    sa.Column('minimum_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('monthly_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_statement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_number', sa.String(), nullable=True),
    sa.Column('swift_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_balance >= 0', name='check_available_balance'),
    sa.CheckConstraint('current_balance >= -overdraft_limit', name='check_balance_overdraft'),
    sa.CheckConstraint('interest_rate >= 0 AND interest_rate <= 1', name='check_interest_rate'),
    sa.CheckConstraint('length(currency) = 3', name='check_currency_length'),
    sa.CheckConstraint('minimum_balance >= 0', name='check_minimum_balance'),
    sa.CheckConstraint('monthly_fee >= 0', name='check_monthly_fee'),
    sa.CheckConstraint('overdraft_limit >= 0', name='check_overdraft_limit'),
    sa.CheckConstraint('pending_balance >= 0', name='check_pending_balance'),
    sa.CheckConstraint('reserved_balance >= 0', name='check_reserved_balance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_primary', name='unique_primary_account_per_user')
    )
    op.create_index('idx_account_status_type', 'accounts', ['status', 'account_type'], unique=False)
    op.create_index('idx_account_user_type', 'accounts', ['user_id', 'account_type'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_currency'), 'accounts', ['currency'], unique=False)
    op.create_index(op.f('ix_accounts_is_primary'), 'accounts', ['is_primary'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('p2p_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_p2p_date', 'p2p_transactions', ['requested_date'], unique=False)
    op.create_index('idx_p2p_recipient', 'p2p_transactions', ['recipient_id'], unique=False)
    op.create_index('idx_p2p_sender', 'p2p_transactions', ['sender_id'], unique=False)
    op.create_index('idx_p2p_status', 'p2p_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_p2p_transactions_recipient_id'), 'p2p_transactions', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_p2p_transactions_sender_id'), 'p2p_transactions', ['sender_id'], unique=False)
    op.create_table('transfer_quotes',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('from_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.JSON(), nullable=True),
    sa.Column('transfer_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('exchange_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_fees', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exchange_fee >= 0', name='check_quote_exchange_fee_non_negative'),
    sa.CheckConstraint('expires_at > created_at', name='check_quote_expires_after_created'),
    sa.CheckConstraint('from_amount > 0', name='check_quote_from_amount_positive'),
    sa.CheckConstraint('length(from_currency) = 3', name='check_quote_from_currency_length'),
    sa.CheckConstraint('length(to_currency) = 3', name='check_quote_to_currency_length'),
    sa.CheckConstraint('to_amount > 0', name='check_quote_to_amount_positive'),
    sa.CheckConstraint('total_cost > 0', name='check_quote_total_cost_positive'),
    sa.CheckConstraint('total_fees >= 0', name='check_quote_total_fees_non_negative'),
    sa.CheckConstraint('transfer_fee >= 0', name='check_quote_transfer_fee_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_index('idx_transfer_quotes_expires', 'transfer_quotes', ['expires_at'], unique=False)
    op.create_index('idx_transfer_quotes_user_expires', 'transfer_quotes', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_transfer_quotes_expires_at'), 'transfer_quotes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_transfer_quotes_user_id'), 'transfer_quotes', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('card_number_masked', sa.String(), nullable=False),
    sa.Column('card_type', sa.Enum('DEBIT', 'CREDIT', 'PREPAID', name='cardtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'EXPIRED', 'CANCELLED', name='cardstatusenum'), nullable=True),
    sa.Column('cardholder_name', sa.String(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('is_contactless_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_online_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_international_enabled', sa.Boolean(), nullable=True),
    sa.Column('pin_set', sa.Boolean(), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=True),
    sa.Column('last_used_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('activation_date >= issued_date OR activation_date IS NULL', name='check_activation_after_issued'),
    sa.CheckConstraint('daily_limit > 0', name='check_daily_limit_positive'),
    sa.CheckConstraint('expiry_month >= 1 AND expiry_month <= 12', name='check_expiry_month'),
    sa.CheckConstraint('expiry_year >= 2020 AND expiry_year <= 2050', name='check_expiry_year'),
    sa.CheckConstraint('failed_pin_attempts >= 0 AND failed_pin_attempts <= 10', name='check_failed_pin_attempts'),
    sa.CheckConstraint('monthly_limit > 0', name='check_monthly_limit_positive'),
    sa.CheckConstraint('monthly_limit >= daily_limit', name='check_monthly_limit_greater_than_daily'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number_masked')
    )
    op.create_index('idx_card_account_type', 'cards', ['account_id', 'card_type'], unique=False)
    op.create_index('idx_card_expiry', 'cards', ['expiry_year', 'expiry_month'], unique=False)
    op.create_index('idx_card_user_status', 'cards', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_cards_account_id'), 'cards', ['account_id'], unique=False)
    op.create_index(op.f('ix_cards_card_type'), 'cards', ['card_type'], unique=False)
    op.create_index(op.f('ix_cards_status'), 'cards', ['status'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investments_account_id', 'investments', ['account_id'], unique=False)
    op.create_index('idx_investments_purchase_date', 'investments', ['purchase_date'], unique=False)
    op.create_index('idx_investments_symbol', 'investments', ['symbol'], unique=False)
    op.create_index('idx_investments_type', 'investments', ['investment_type'], unique=False)
    op.create_index('idx_investments_user_id', 'investments', ['user_id'], unique=False)
    op.create_index(op.f('ix_investments_account_id'), 'investments', ['account_id'], unique=False)
    op.create_index(op.f('ix_investments_user_id'), 'investments', ['user_id'], unique=False)
    op.create_table('money_transfers',
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_account_id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('destination_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('destination_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate_used', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('transfer_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('exchange_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_fees', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('recipient_message', sa.Text(), nullable=True),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.Column('compliance_check_passed', sa.Boolean(), nullable=True),
    sa.Column('requires_documents', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('standard', 'express', 'urgent')", name='check_transfer_priority'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'in_transit', 'completed', 'failed', 'cancelled', 'returned', 'on_hold')", name='check_transfer_status'),
    sa.CheckConstraint('destination_amount > 0', name='check_transfer_destination_amount_positive'),
    sa.CheckConstraint('exchange_fee >= 0', name='check_transfer_exchange_fee_non_negative'),
    sa.CheckConstraint('exchange_rate_used > 0', name='check_transfer_exchange_rate_positive'),
    sa.CheckConstraint('initiated_at <= processed_at OR processed_at IS NULL', name='check_transfer_processed_after_initiated'),
    sa.CheckConstraint('length(destination_currency) = 3', name='check_transfer_destination_currency_length'),
    sa.CheckConstraint('length(source_currency) = 3', name='check_transfer_source_currency_length'),
    sa.CheckConstraint('processed_at <= completed_at OR completed_at IS NULL', name='check_transfer_completed_after_processed'),
    sa.CheckConstraint('source_amount > 0', name='check_transfer_source_amount_positive'),
    sa.CheckConstraint('total_cost > 0', name='check_transfer_total_cost_positive'),
    sa.CheckConstraint('total_fees >= 0', name='check_transfer_total_fees_non_negative'),
    sa.CheckConstraint('transfer_fee >= 0', name='check_transfer_fee_non_negative'),
    sa.ForeignKeyConstraint(['quote_id'], ['transfer_quotes.quote_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index('idx_money_transfers_external_ref', 'money_transfers', ['external_reference'], unique=False)
    op.create_index('idx_money_transfers_status_date', 'money_transfers', ['status', 'initiated_at'], unique=False)
    op.create_index('idx_money_transfers_type_date', 'money_transfers', ['transfer_type', 'initiated_at'], unique=False)
    op.create_index('idx_money_transfers_user_status', 'money_transfers', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_money_transfers_beneficiary_id'), 'money_transfers', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_money_transfers_external_reference'), 'money_transfers', ['external_reference'], unique=False)
    op.create_index(op.f('ix_money_transfers_source_account_id'), 'money_transfers', ['source_account_id'], unique=False)
    op.create_index(op.f('ix_money_transfers_status'), 'money_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_money_transfers_transfer_type'), 'money_transfers', ['transfer_type'], unique=False)
    op.create_index(op.f('ix_money_transfers_user_id'), 'money_transfers', ['user_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('from_account_id', sa.String(), nullable=False),
    sa.Column('to_account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fee_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfers_date', 'transfers', ['requested_date'], unique=False)
    op.create_index('idx_transfers_from_account', 'transfers', ['from_account_id'], unique=False)
    op.create_index('idx_transfers_status', 'transfers', ['status'], unique=False)
    op.create_index('idx_transfers_to_account', 'transfers', ['to_account_id'], unique=False)
    op.create_index('idx_transfers_user_id', 'transfers', ['user_id'], unique=False)
    op.create_index(op.f('ix_transfers_user_id'), 'transfers', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT', 'PAYMENT', 'REFUND', 'FEE', 'INTEREST', 'DIVIDEND', 'PURCHASE', 'SALE', 'ATM_WITHDRAWAL', 'CARD_PAYMENT', 'MOBILE_PAYMENT', 'BILL_PAYMENT', 'SALARY', 'LOAN_PAYMENT', 'INVESTMENT', 'OTHER', name='transactiontypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', name='transactionstatusenum'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='transactiondirectionenum'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('original_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('merchant_category', sa.Enum('GROCERIES', 'RESTAURANTS', 'GAS_STATIONS', 'RETAIL', 'ENTERTAINMENT', 'TRAVEL', 'HEALTHCARE', 'UTILITIES', 'EDUCATION', 'AUTOMOTIVE', 'HOME_IMPROVEMENT', 'INSURANCE', 'PROFESSIONAL_SERVICES', 'GOVERNMENT', 'CHARITY', 'ONLINE_SERVICES', 'SUBSCRIPTION', 'ATM_FEE', 'BANK_FEE', 'TRANSFER', 'INVESTMENT_TRADE', 'CASH_ADVANCE', 'OTHER', name='merchantcategoryenum'), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CASH', 'CHECK', 'WIRE', 'ACH', 'CRYPTO', 'OTHER', name='paymentmethodenum'), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('balance_after', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('is_disputed', sa.Boolean(), nullable=True),
    sa.Column('is_fraudulent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_transaction_amount_positive'),
    sa.CheckConstraint('exchange_rate > 0', name='check_exchange_rate_positive'),
    sa.CheckConstraint('fee_amount >= 0', name='check_fee_amount_non_negative'),
    sa.CheckConstraint('length(currency) = 3', name='check_transaction_currency_length'),
    sa.CheckConstraint('length(original_currency) = 3', name='check_original_currency_length'),
    sa.CheckConstraint('original_amount > 0', name='check_original_amount_positive'),
    sa.CheckConstraint('transaction_date <= posted_date OR posted_date IS NULL', name='check_transaction_posted_date_order'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_account_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_merchant_date', 'transactions', ['merchant_category', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_status_date', 'transactions', ['status', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_type_date', 'transactions', ['transaction_type', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_direction'), 'transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_transactions_is_disputed'), 'transactions', ['is_disputed'], unique=False)
    op.create_index(op.f('ix_transactions_is_fraudulent'), 'transactions', ['is_fraudulent'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_category'), 'transactions', ['merchant_category'], unique=False)
    op.create_index(op.f('ix_transactions_reference_number'), 'transactions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_fraudulent'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_disputed'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_direction'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('idx_transaction_user_date', table_name='transactions')
    op.drop_index('idx_transaction_type_date', table_name='transactions')
    op.drop_index('idx_transaction_status_date', table_name='transactions')
    op.drop_index('idx_transaction_merchant_date', table_name='transactions')
    op.drop_index('idx_transaction_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transfers_user_id'), table_name='transfers')
    op.drop_index('idx_transfers_user_id', table_name='transfers')
    op.drop_index('idx_transfers_to_account', table_name='transfers')
    op.drop_index('idx_transfers_status', table_name='transfers')
    op.drop_index('idx_transfers_from_account', table_name='transfers')
    op.drop_index('idx_transfers_date', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_money_transfers_user_id'), table_name='money_transfers')
    op.drop_index(op.f('ix_money_transfers_transfer_type'), table_name='money_transfers')
    op.drop_index(op.f('ix_money_transfers_status'), table_name='money_transfers')
    op.drop_index(op.f('ix_money_transfers_source_account_id'), table_name='money_transfers')
    op.drop_index(op.f('ix_money_transfers_external_reference'), table_name='money_transfers')
    op.drop_index(op.f('ix_money_transfers_beneficiary_id'), table_name='money_transfers')
    op.drop_index('idx_money_transfers_user_status', table_name='money_transfers')
    op.drop_index('idx_money_transfers_type_date', table_name='money_transfers')
    op.drop_index('idx_money_transfers_status_date', table_name='money_transfers')
    op.drop_index('idx_money_transfers_external_ref', table_name='money_transfers')
    op.drop_table('money_transfers')
    op.drop_index(op.f('ix_investments_user_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_account_id'), table_name='investments')
    op.drop_index('idx_investments_user_id', table_name='investments')
    op.drop_index('idx_investments_type', table_name='investments')
    op.drop_index('idx_investments_symbol', table_name='investments')
    op.drop_index('idx_investments_purchase_date', table_name='investments')
    op.drop_index('idx_investments_account_id', table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_status'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_type'), table_name='cards')
    op.drop_index(op.f('ix_cards_account_id'), table_name='cards')
    op.drop_index('idx_card_user_status', table_name='cards')
    op.drop_index('idx_card_expiry', table_name='cards')
    op.drop_index('idx_card_account_type', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_transfer_quotes_user_id'), table_name='transfer_quotes')
    op.drop_index(op.f('ix_transfer_quotes_expires_at'), table_name='transfer_quotes')
    op.drop_index('idx_transfer_quotes_user_expires', table_name='transfer_quotes')
    op.drop_index('idx_transfer_quotes_expires', table_name='transfer_quotes')
    op.drop_table('transfer_quotes')
    op.drop_index(op.f('ix_p2p_transactions_sender_id'), table_name='p2p_transactions')
    op.drop_index(op.f('ix_p2p_transactions_recipient_id'), table_name='p2p_transactions')
    op.drop_index('idx_p2p_status', table_name='p2p_transactions')
    op.drop_index('idx_p2p_sender', table_name='p2p_transactions')
    op.drop_index('idx_p2p_recipient', table_name='p2p_transactions')
    op.drop_index('idx_p2p_date', table_name='p2p_transactions')
    op.drop_table('p2p_transactions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_primary'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_currency'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_index('idx_account_user_type', table_name='accounts')
    op.drop_index('idx_account_status_type', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
