"""Add database indexes and authentication enhancements

Revision ID: d6050fb39b20
Revises: e186d7e75090
Create Date: 2025-09-08 13:51:54.678773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6050fb39b20'
down_revision: Union[str, None] = 'e186d7e75090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_accounts_number', 'accounts', ['account_number'], unique=False)
    op.create_index('idx_accounts_primary', 'accounts', ['is_primary'], unique=False)
    op.create_index('idx_accounts_status', 'accounts', ['status'], unique=False)
    op.create_index('idx_accounts_type', 'accounts', ['account_type'], unique=False)
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('idx_accounts_user_type', 'accounts', ['user_id', 'account_type'], unique=False)
    op.create_index('idx_cards_account_id', 'cards', ['account_id'], unique=False)
    op.create_index('idx_cards_expiry', 'cards', ['expiry_year', 'expiry_month'], unique=False)
    op.create_index('idx_cards_status', 'cards', ['status'], unique=False)
    op.create_index('idx_cards_type', 'cards', ['card_type'], unique=False)
    op.create_index('idx_cards_user_id', 'cards', ['user_id'], unique=False)
    op.create_index('idx_investments_account_id', 'investments', ['account_id'], unique=False)
    op.create_index('idx_investments_purchase_date', 'investments', ['purchase_date'], unique=False)
    op.create_index('idx_investments_symbol', 'investments', ['symbol'], unique=False)
    op.create_index('idx_investments_type', 'investments', ['investment_type'], unique=False)
    op.create_index('idx_investments_user_id', 'investments', ['user_id'], unique=False)
    op.create_index('idx_p2p_date', 'p2p_transactions', ['requested_date'], unique=False)
    op.create_index('idx_p2p_recipient', 'p2p_transactions', ['recipient_id'], unique=False)
    op.create_index('idx_p2p_sender', 'p2p_transactions', ['sender_id'], unique=False)
    op.create_index('idx_p2p_status', 'p2p_transactions', ['status'], unique=False)
    op.create_index('idx_transactions_account_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('idx_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transactions_direction', 'transactions', ['direction'], unique=False)
    op.create_index('idx_transactions_merchant', 'transactions', ['merchant_category'], unique=False)
    op.create_index('idx_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transactions_status_date', 'transactions', ['status', 'transaction_date'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['transaction_type'], unique=False)
    op.create_index('idx_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('idx_transfers_date', 'transfers', ['requested_date'], unique=False)
    op.create_index('idx_transfers_from_account', 'transfers', ['from_account_id'], unique=False)
    op.create_index('idx_transfers_status', 'transfers', ['status'], unique=False)
    op.create_index('idx_transfers_to_account', 'transfers', ['to_account_id'], unique=False)
    op.create_index('idx_transfers_user_id', 'transfers', ['user_id'], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_index('idx_transfers_user_id', table_name='transfers')
    op.drop_index('idx_transfers_to_account', table_name='transfers')
    op.drop_index('idx_transfers_status', table_name='transfers')
    op.drop_index('idx_transfers_from_account', table_name='transfers')
    op.drop_index('idx_transfers_date', table_name='transfers')
    op.drop_index('idx_transactions_user_id', table_name='transactions')
    op.drop_index('idx_transactions_user_date', table_name='transactions')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_status_date', table_name='transactions')
    op.drop_index('idx_transactions_status', table_name='transactions')
    op.drop_index('idx_transactions_merchant', table_name='transactions')
    op.drop_index('idx_transactions_direction', table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_account_id', table_name='transactions')
    op.drop_index('idx_transactions_account_date', table_name='transactions')
    op.drop_index('idx_p2p_status', table_name='p2p_transactions')
    op.drop_index('idx_p2p_sender', table_name='p2p_transactions')
    op.drop_index('idx_p2p_recipient', table_name='p2p_transactions')
    op.drop_index('idx_p2p_date', table_name='p2p_transactions')
    op.drop_index('idx_investments_user_id', table_name='investments')
    op.drop_index('idx_investments_type', table_name='investments')
    op.drop_index('idx_investments_symbol', table_name='investments')
    op.drop_index('idx_investments_purchase_date', table_name='investments')
    op.drop_index('idx_investments_account_id', table_name='investments')
    op.drop_index('idx_cards_user_id', table_name='cards')
    op.drop_index('idx_cards_type', table_name='cards')
    op.drop_index('idx_cards_status', table_name='cards')
    op.drop_index('idx_cards_expiry', table_name='cards')
    op.drop_index('idx_cards_account_id', table_name='cards')
    op.drop_index('idx_accounts_user_type', table_name='accounts')
    op.drop_index('idx_accounts_user_id', table_name='accounts')
    op.drop_index('idx_accounts_type', table_name='accounts')
    op.drop_index('idx_accounts_status', table_name='accounts')
    op.drop_index('idx_accounts_primary', table_name='accounts')
    op.drop_index('idx_accounts_number', table_name='accounts')
    # ### end Alembic commands ###
